# --spring.profiles.active=dev
# Set SPRING_PROFILES_ACTIVE environment variable
spring:
  profiles:
    active: @spring.profiles.active@

my-value: application
---
# This is an example for a profile in the same file
spring:
  config:
    activate:
      on-profile: test
my-value: test-application