# --spring.profiles.active=dev
# Set SPRING_PROFILES_ACTIVE environment variable
spring:
  profiles:
    active: local

my-value: application
---
spring:
  config:
    activate:
      on-profile: test
my-value: test-application